#!/usr/bin/env python3
"""
x-tweetcraft credential setup script (interactive, secure)

Prompts the user for X API credentials using getpass (input hidden from screen),
then writes them to ~/.x-tweetcraft.env with secure permissions (600).

Usage:
    python3 setup-credentials.py

Security properties:
    - Input is NOT echoed to the terminal (getpass)
    - Credentials are NOT logged to shell history
    - File is created with 600 permissions (owner read/write only)
    - File is placed outside the plugin repo (user's home directory)

After running this script, the MCP server can read credentials from
~/.x-tweetcraft.env via python-dotenv.
"""

import os
import stat
import sys
from getpass import getpass
from pathlib import Path

ENV_FILE = Path.home() / ".x-tweetcraft.env"

CREDENTIALS = [
    ("X_BEARER_TOKEN", "Bearer Token"),
    ("X_API_KEY", "API Key (Consumer Key)"),
    ("X_API_SECRET", "API Key Secret (Consumer Secret)"),
    ("X_ACCESS_TOKEN", "Access Token"),
    ("X_ACCESS_TOKEN_SECRET", "Access Token Secret"),
]


def confirm_overwrite() -> bool:
    """Ask the user before overwriting an existing credentials file."""
    if not ENV_FILE.exists():
        return True
    print(f"\n⚠️  {ENV_FILE} は既に存在します。")
    answer = input("上書きしますか？ (y/N): ").strip().lower()
    return answer == "y"


def prompt_credentials() -> dict[str, str]:
    """Securely prompt for each credential. Returns dict of env_var -> value."""
    print("\nX Developer Portal の Keys and tokens タブで取得した値を入力してください。")
    print("入力は画面に表示されません（セキュリティのため）。\n")
    print("貼り付け: Cmd+V (macOS) / Ctrl+Shift+V (Linux) / 右クリック (Windows)")
    print("スキップ: 空のままEnter（後で手動編集）\n")

    values: dict[str, str] = {}
    for env_var, display_name in CREDENTIALS:
        value = getpass(f"{display_name} を入力: ").strip()
        values[env_var] = value
    return values


def write_env_file(values: dict[str, str]) -> None:
    """Write credentials to ~/.x-tweetcraft.env with 600 permissions."""
    lines = [
        "# X Developer API credentials for x-tweetcraft",
        "# Get these from https://developer.x.com/en/portal/dashboard",
        "# Generated by setup-credentials.py",
        "",
    ]
    for env_var, _ in CREDENTIALS:
        lines.append(f"{env_var}={values.get(env_var, '')}")

    # Write the file
    ENV_FILE.write_text("\n".join(lines) + "\n")

    # Set permissions to 600 (owner read/write only)
    ENV_FILE.chmod(stat.S_IRUSR | stat.S_IWUSR)


def verify_file() -> None:
    """Verify the file exists with correct permissions."""
    if not ENV_FILE.exists():
        print(f"❌ ファイル作成に失敗しました: {ENV_FILE}", file=sys.stderr)
        sys.exit(1)

    mode = ENV_FILE.stat().st_mode & 0o777
    if mode != 0o600:
        print(
            f"⚠️  警告: ファイル権限が 600 ではありません (現在: {oct(mode)})",
            file=sys.stderr,
        )

    # Count empty credentials (for user feedback, without revealing values)
    content = ENV_FILE.read_text()
    empty_count = sum(
        1
        for line in content.splitlines()
        if line.startswith("X_") and line.endswith("=")
    )

    print(f"\n✅ 認証情報を保存しました: {ENV_FILE}")
    print(f"   権限: {oct(mode)}")
    if empty_count > 0:
        print(
            f"⚠️  {empty_count}個の項目が未入力です。"
            f"後で再実行するか、エディタで直接編集してください。"
        )
    else:
        print("   すべての項目が入力されています。")


def main() -> None:
    print("=" * 60)
    print("x-tweetcraft 認証情報セットアップ")
    print("=" * 60)

    if not confirm_overwrite():
        print("キャンセルしました。")
        sys.exit(0)

    values = prompt_credentials()
    write_env_file(values)
    verify_file()

    print("\n次のステップ:")
    print("  1. Claude Code でx-tweetcraft が認識しているか確認")
    print("  2. 「自分の投稿分析して」など API機能を呼ぶスキルを試す")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n中断しました。", file=sys.stderr)
        sys.exit(130)
